/**
 * Formatting Voice Commands
 *
 * Commands for text formatting:
 * - Bold, italic, strikethrough, code
 * - Headings (1-6)
 * - Quote, code block
 */

import type { VoiceCommand } from '@/types/voiceCommand';
import type { CursorLocation, ViewMode, VoicePhase } from '@/types/editorContext';
import { commandRegistry } from '../commandRegistry';

// Common allowed locations for text formatting
const TEXT_LOCATIONS: CursorLocation[] = ['paragraph', 'heading', 'list', 'blockquote'];

// Common allowed view modes (not preview-only)
const EDIT_VIEW_MODES: ViewMode[] = ['editor', 'split'];

// Voice phases where commands can be executed
const COMMAND_PHASES: VoicePhase[] = ['listening', 'command-recognized'];

/**
 * Dispatch a command to the editor
 * Uses custom event that Editor.tsx listens for
 */
function dispatchEditorCommand(command: string, payload?: Record<string, unknown>) {
  window.dispatchEvent(
    new CustomEvent('mutter:execute-command', {
      detail: { command, ...payload },
    })
  );
}

const formattingCommands: VoiceCommand[] = [
  // Inline formatting (requires selection)
  {
    id: 'format-bold',
    name: 'Bold selection',
    examples: ['bold', 'make bold', 'bold this', 'make it bold'],
    bucket: 'edit-selection',
    requiresSelection: true,
    requiresNote: true,
    allowedLocations: TEXT_LOCATIONS,
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'inline',
    reversible: true,
    action: () => dispatchEditorCommand('bold'),
  },
  {
    id: 'format-italic',
    name: 'Italicize selection',
    examples: ['italic', 'italicize', 'make italic', 'emphasize'],
    bucket: 'edit-selection',
    requiresSelection: true,
    requiresNote: true,
    allowedLocations: TEXT_LOCATIONS,
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'inline',
    reversible: true,
    action: () => dispatchEditorCommand('italic'),
  },
  {
    id: 'format-strikethrough',
    name: 'Strikethrough',
    examples: ['strikethrough', 'strike through', 'cross out', 'strike'],
    bucket: 'edit-selection',
    requiresSelection: true,
    requiresNote: true,
    allowedLocations: TEXT_LOCATIONS,
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'inline',
    reversible: true,
    action: () => dispatchEditorCommand('strikethrough'),
  },
  {
    id: 'format-code-inline',
    name: 'Inline code',
    examples: ['code', 'inline code', 'make code', 'monospace'],
    bucket: 'edit-selection',
    requiresSelection: true,
    requiresNote: true,
    allowedLocations: TEXT_LOCATIONS,
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'inline',
    reversible: true,
    action: () => dispatchEditorCommand('code'),
  },

  // Heading commands (work on current line)
  {
    id: 'format-heading-1',
    name: 'Heading 1',
    examples: ['heading 1', 'h1', 'make heading 1', 'title'],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('heading', { level: 1 }),
  },
  {
    id: 'format-heading-2',
    name: 'Heading 2',
    examples: ['heading 2', 'h2', 'make heading 2', 'section'],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('heading', { level: 2 }),
  },
  {
    id: 'format-heading-3',
    name: 'Heading 3',
    examples: ['heading 3', 'h3', 'make heading 3', 'subsection'],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('heading', { level: 3 }),
  },
  {
    id: 'format-heading-4',
    name: 'Heading 4',
    examples: ['heading 4', 'h4', 'make heading 4'],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('heading', { level: 4 }),
  },
  {
    id: 'format-heading-5',
    name: 'Heading 5',
    examples: ['heading 5', 'h5', 'make heading 5'],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('heading', { level: 5 }),
  },
  {
    id: 'format-heading-6',
    name: 'Heading 6',
    examples: ['heading 6', 'h6', 'make heading 6'],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('heading', { level: 6 }),
  },

  // Block formatting
  {
    id: 'format-quote',
    name: 'Block quote',
    examples: ['quote', 'block quote', 'make quote', 'quotation'],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'list', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('quote'),
  },
  {
    id: 'format-code-block',
    name: 'Code block',
    examples: ['code block', 'code fence', 'fenced code', 'make code block'],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('codeBlock'),
  },

  // ====================================
  // List Commands (Phase 2)
  // ====================================
  {
    id: 'format-bullet-list',
    name: 'Bullet list',
    examples: [
      'bullet list',
      'bullet point',
      'make bullet list',
      'add bullet',
      'unordered list',
      'bullets',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('bulletList'),
  },
  {
    id: 'format-numbered-list',
    name: 'Numbered list',
    examples: [
      'numbered list',
      'number list',
      'ordered list',
      'make numbered list',
      'add number',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('numberedList'),
  },
  {
    id: 'format-task-list',
    name: 'Task list',
    examples: [
      'task list',
      'checkbox list',
      'todo list',
      'make task',
      'add checkbox',
      'checklist',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'heading', 'list', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('taskList'),
  },
  {
    id: 'format-toggle-checkbox',
    name: 'Toggle checkbox',
    examples: [
      'check',
      'uncheck',
      'toggle checkbox',
      'mark done',
      'mark complete',
      'complete task',
      'finish task',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['list'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('toggleCheckbox'),
  },
  {
    id: 'format-indent-list',
    name: 'Indent list item',
    examples: [
      'indent',
      'indent list',
      'indent item',
      'tab',
      'nest',
      'move right',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['list'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('indentList'),
  },
  {
    id: 'format-outdent-list',
    name: 'Outdent list item',
    examples: [
      'outdent',
      'outdent list',
      'outdent item',
      'shift tab',
      'unnest',
      'move left',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['list'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('outdentList'),
  },
  {
    id: 'format-remove-list',
    name: 'Remove list formatting',
    examples: [
      'remove list',
      'no list',
      'clear list',
      'make paragraph',
      'remove bullet',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['list'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'low',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('removeList'),
  },

  // ====================================
  // Quick Insert Commands (Phase 2)
  // ====================================
  {
    id: 'format-horizontal-rule',
    name: 'Horizontal rule',
    examples: [
      'horizontal rule',
      'divider',
      'separator',
      'line break',
      'add divider',
      'insert line',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('horizontalRule'),
  },
  {
    id: 'format-callout',
    name: 'Insert callout',
    examples: [
      'callout',
      'add callout',
      'insert callout',
      'note box',
      'info box',
      'warning box',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('insertCallout'),
  },
  {
    id: 'format-highlight',
    name: 'Highlight text',
    examples: [
      'highlight',
      'highlight this',
      'mark highlight',
      'yellow highlight',
    ],
    bucket: 'edit-selection',
    requiresSelection: true,
    requiresNote: true,
    allowedLocations: TEXT_LOCATIONS,
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'inline',
    reversible: true,
    action: () => dispatchEditorCommand('highlight'),
  },

  // ====================================
  // Table Commands (Phase 2)
  // ====================================
  {
    id: 'format-insert-table',
    name: 'Insert table',
    examples: [
      'insert table',
      'add table',
      'create table',
      'new table',
      'make table',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph', 'empty'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('insertTable'),
  },
  {
    id: 'format-add-table-row',
    name: 'Add table row',
    examples: [
      'add row',
      'new row',
      'insert row',
      'add table row',
      'row below',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph'], // Must be in table context
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('addTableRow'),
  },
  {
    id: 'format-add-table-column',
    name: 'Add table column',
    examples: [
      'add column',
      'new column',
      'insert column',
      'add table column',
      'column right',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('addTableColumn'),
  },
  {
    id: 'format-delete-table-row',
    name: 'Delete table row',
    examples: [
      'delete row',
      'remove row',
      'delete table row',
      'remove this row',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'low',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('deleteTableRow'),
  },
  {
    id: 'format-delete-table-column',
    name: 'Delete table column',
    examples: [
      'delete column',
      'remove column',
      'delete table column',
      'remove this column',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'low',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('deleteTableColumn'),
  },
  {
    id: 'format-next-cell',
    name: 'Next table cell',
    examples: [
      'next cell',
      'next column',
      'tab',
      'move right',
    ],
    bucket: 'navigate',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'inline',
    reversible: true,
    action: () => dispatchEditorCommand('nextTableCell'),
  },
  {
    id: 'format-previous-cell',
    name: 'Previous table cell',
    examples: [
      'previous cell',
      'previous column',
      'shift tab',
      'move left',
    ],
    bucket: 'navigate',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'inline',
    reversible: true,
    action: () => dispatchEditorCommand('previousTableCell'),
  },
  {
    id: 'format-align-left',
    name: 'Align column left',
    examples: [
      'align left',
      'left align',
      'align column left',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('alignTableLeft'),
  },
  {
    id: 'format-align-center',
    name: 'Align column center',
    examples: [
      'align center',
      'center align',
      'center column',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('alignTableCenter'),
  },
  {
    id: 'format-align-right',
    name: 'Align column right',
    examples: [
      'align right',
      'right align',
      'align column right',
    ],
    bucket: 'format-text',
    requiresSelection: false,
    requiresNote: true,
    allowedLocations: ['paragraph'],
    allowedViewModes: EDIT_VIEW_MODES,
    allowedVoicePhases: COMMAND_PHASES,
    destructiveness: 'none',
    scope: 'block',
    reversible: true,
    action: () => dispatchEditorCommand('alignTableRight'),
  },
];

/**
 * Register all formatting commands
 */
export function registerFormattingCommands(): void {
  commandRegistry.registerAll(formattingCommands);
}

export { formattingCommands };
